### ISSUE TITLE
Follow up on refactor

### ISSUE THREAD

**Issue by rom1504** [rom1504/img2dataset#79]
* [ ] implement another writer to validate the concept #82 
* [ ] create the distributor #20 
* [x] make reader more efficient #80 
* [x]  #75

**Comment by rom1504** [comment]
this is done
